name: greenhub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0
  firebase_app_check: ^0.4.4+1

  # State Management
  flutter_riverpod: ^3.3.1

  # Navigation
  go_router: ^17.2.0

  # Utilities
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  uuid: ^4.5.3

  # UI
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.10
  flutter_stripe: ^13.0.0
  cloud_functions: ^6.3.3
  tflite_flutter: ^0.12.1

  # Reports
  pdf: ^3.11.3
  printing: ^5.13.4
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/logo_icon_only.png"
  background_color: "#2D6A4F"
  adaptive_icon_background: "#2D6A4F"
  adaptive_icon_foreground: "assets/logo/logo_icon_only.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/models/crop_demand.tflite
